import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Tejasri",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "sony",
      email: "sony@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
    {
      name: "kiran",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
    {
      name: "divija",
      email: "user1@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],

  /*  products: [
    {
      name: "Nike Slim Shirt",
      category: "shirt",
      image: "/images/girl.jpeg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 20,
      description: "High quality product",
    },
    {
      name: "Only  Shirt",
      category: "shirt",
      image: "/images/shirt1.jpg",
      price: 150,
      countInStock: 30,
      brand: "only",
      rating: 3.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      name: "Lee cooper Shirt",
      category: "shirt",
      image: "/images/shirt2.jpg",
      price: 110,
      countInStock: 0,
      brand: "Lee cooper",
      rating: 4.8,
      numReviews: 15,
      description: "High quality product",
    },
    {
      name: "Harpa Shirt",
      category: "shirt",
      image: "/images/shirt3.jpg",
      price: 100,
      countInStock: 10,
      brand: "harpa",
      rating: 4.5,
      numReviews: 30,
      description: "High quality product",
    },
    {
      name: "Allen solly Shirt",
      category: "shirt",
      image: "/images/shirt4.jpg",
      price: 150,
      countInStock: 10,
      brand: "Allen",
      rating: 2.5,
      numReviews: 5,
      description: "High quality product",
    },
    {
      name: "pepe jeans",
      category: "shirt",
      image: "/images/shirt5.jpg",
      price: 160,
      countInStock: 15,
      brand: "Pepe",
      rating: 1.5,
      numReviews: 3,
      description: "High quality product",
    },
  ], */
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};

export default data;
