export const PRODUCT_LIST_REQUEST = 'PRODUCT__LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT__LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT__LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT__DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT__DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT__DETAILS_FAIL';


